### ISSUE TITLE
ng build --prod fail

### ISSUE THREAD

**Issue by sggonzalezg** [lexzhukov/ngx-siema#47]
When I run ng build --prod this fail and make this [ERROR]

'Supplied parameters do not match any signature of call target'

Please help

**Comment by lexzhukov** [comment]
@sggonzalezg thanks for bug report. Could you provide more details and code example?

**Comment by lexzhukov** [comment]
@sggonzalezg try to update ngx-siema to the latest 1.2.0 version.

**Comment by ederribeiro** [comment]
Hi @lexzhukov,

Same problem here.

My ngx-version is 1.2.0

Thanks.

**Comment by ederribeiro** [comment]
Hi @lexzhukov and @sggonzalezg,

I solved this problem, just passing a parameter to the buttons functions like this `(click) ="onNext (1) "`.

This error occurred because the class function have expect a parameter.
`
onNext(numbers: number) {
    this.siema.onNext(numbers);
  }
`
