### ISSUE TITLE
Unable to create multiple carousel

### ISSUE THREAD

**Issue by Santhosh25** [lexzhukov/ngx-siema#49]
Unable to create multiple carousel in single page. I tried, example of usage with the navigation buttons based on your document. The first slider component is getting instantiated but remaining doesn't. Could please tell me how can i achieve this?

**Comment by lexzhukov** [comment]
@Santhosh25 for multiple carousels in single page use the tags like:
`<ngx-siema #firstCarousel></ngx-siema>` and `@ViewChild('firstCarousel') carousel`.

**Comment by leo6104** [comment]
You can use multiple carousel with  adding selector property.

This code work for me 
```
      <ngx-siema #phoneCarousel [options]="options" selector="siema">
        <ngx-siema-slide>
          <img src="~" width="100%">
        </ngx-siema-slide>
        <ngx-siema-slide>
          <img src="~" width="100%">
        </ngx-siema-slide>
      </ngx-siema>

      <ngx-siema #binderCarousel [options]="options" selector="siema2">
        <ngx-siema-slide>
          <img src="~" width="100%">
        </ngx-siema-slide>
        <ngx-siema-slide>
          <img src="~" width="100%">
        </ngx-siema-slide>
      </ngx-siema>
```

**Comment by TaerMosa** [comment]
can you give an example for the selector component

**Comment by TaerMosa** [comment]
Or if you can add a full example for how to use a list of two Carousals using  ngx-siema to npmjs
Thanks

**Comment by leo6104** [comment]
@TaerMosa You can use above code. Just give string for selector. 

I found this method from siema component code. - 44 line. 
https://github.com/lexzhukov/ngx-siema/blob/master/src/siema.component.ts#L44

@Input() selector: string = 'siema'; 
it will create <div class='siema'>

If you use ngx-siema component with <ngx-siema selector="siema2">, 
It will create <div class='siema2'>

**Comment by TaerMosa** [comment]
Thanks its working now 👍 
there is a problem with using goto() function as a value for (Click) button , 
for example , if I am using 2  <ngx-siema> and for each one i need a button with (Click) = goto(slid_num)
its not working for the second carousal .and i don't want to use the function as an $event .

**Comment by lexzhukov** [comment]
Hi, there! I added a possibility of using multiple instances of ngx-siema in 2.0.0 version.

**Comment by Santhosh25** [comment]
Hi, @lexzhukov Thank you so much. Let me try it.
